### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#12]
is SD-Manager creating those webp thumbnails for every image?

![image](https://github.com/albertpb/sd-manager/assets/13394741/ac1b0daa-75c4-445f-b0ff-73d762552ee1)

**Comment by albertpb** [comment]
yes, bigger images would cause stuttering or freeze when you scroll.

**Comment by AsuraAce** [comment]
do they have to be next to each other? if not, a dedicated location for thumbnails would be nice.

**Comment by albertpb** [comment]
To make it easy, I can move all thumbnails to a folder inside the current path of the image

**Comment by AsuraAce** [comment]
sounds good, thank you.

**Comment by AsuraAce** [comment]
added
