### ISSUE TITLE
Unkown Model for Images

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#2]
it seems whenever the model itself is not in the specified folder, SD Manger will display "Unkown" as shown below. It would be nice if SD Manager could get the model information from the exif metadata parameters in those cases.

![image](https://github.com/albertpb/sd-manager/assets/13394741/52cbe2ba-b77c-4f29-87ba-3682cdf07aa7)

**Comment by albertpb** [comment]
I think I fixed the automatic1111 parsing in v1.4.1. Try to rescan images again and tell me if it works.

**Comment by albertpb** [comment]
What is breadboard ?

Those images that weren't found are duplicates from the other folder? The thing is, for sd-manager to avoid import the same image it hashes the image and if that hash is already found in the database, it won't import it. 

Are those images png ?. For now sd-manager only import png images.

When you are importing, can you tell me if is using 100% cpu or 100% disk io ?

**Comment by AsuraAce** [comment]
Breadboard is an image management app for SD, but not maintained anymore. Breadboard was just an example tho, indexing speed within a1111 (extensions like infinity browser) is way faster as well. i think about 30 minutes for 100-150k images in my case.

https://github.com/cocktailpeanut/breadboard
https://breadboard.me/

no, the path i import images from don´t share any images. - i ran into an issue with SD Manager 1.4 and deleted the appdata folder before i started using 1.4.1 (i used a different path (parent directory) to import from my archive with 1.4).

almost all images are png but i think there a couple or a couple dozen jpg images in there was well.

disk io was at 1% when i checked and cpu stayed consistently at around 25%.

**Comment by albertpb** [comment]
In case you move the images folders to a new path and add it to the watch folders, when it scan again it will update the images according to the new path. This will be released in the next version.

I will not support jpg images for now. I want to fix all the bugs first.

I think I will use blake3 or CRC for hashing images instead of sha256 to increase performance.

**Comment by AsuraAce** [comment]
nice, will move all my files to a new drive in the coming days anyway.

**Comment by AsuraAce** [comment]
import speed related issues seem to be fixed. moved everything AI to a new drive and re-imported after a fresh install. took less than 20 minutes for around 80k images.

Unkown Images got fixed as well, will close this one. 
thank you.
