### ISSUE TITLE
"No Image data blocks found." - cmd message in relation to embedding

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#21]
SD-Manager seems to create some folders and thumbnail images for embeddingd, those create minor issues with cmd output, those will display "No Image data blocks found." messages, like a lot of them. 

![image](https://github.com/albertpb/sd-manager/assets/13394741/7126b4ef-522a-4614-902d-6e028c8aad4e)

found this on gitub:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12222

**Comment by albertpb** [comment]
I don't touch the embedding folder, unless you are importing that folder in sd-manager.  
The files that sd-manager creates are .thumbnail.webp for every image imported and the images that are inserted in the markdown text-editor.

**Comment by AsuraAce** [comment]
aight, will close this one and try to figure out where those thumbnails and folder are coming from.
