### ISSUE TITLE
Hashing Images on Start

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#22]
i´m stuck trying to hash images (no progress for 15 minutes on startup):

![image](https://github.com/albertpb/sd-manager/assets/13394741/304050ac-a7ea-41ed-80bb-602819ea6b0f)

edit:
same on 2nd try:
![image](https://github.com/albertpb/sd-manager/assets/13394741/e4b9b251-067b-4cb1-b174-69f9fa3dcd5c)

**Comment by albertpb** [comment]
what version ? , I fixed a bug related to this in v1.5.6.

**Comment by AsuraAce** [comment]
fixed in 1.5.6
