### ISSUE TITLE
No Metadata

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#27]
metadata is missing again (a1111 created images)

![image](https://github.com/albertpb/sd-manager/assets/13394741/4a58ddc2-f6f5-4c41-8afd-49a55855f42f)

![image](https://github.com/albertpb/sd-manager/assets/13394741/67b1ca86-295a-4b76-9ee5-d3ad95a7e420)

**Comment by albertpb** [comment]
In sd-manager drop the image in png info and post the result here pls

**Comment by AsuraAce** [comment]
![image](https://github.com/albertpb/sd-manager/assets/13394741/60a65692-a29f-4064-ae00-89cf3a9e17a9)

**Comment by AsuraAce** [comment]
i think this one was fixed as well, right? will open again if i run into it again with newly generated images
