### ISSUE TITLE
Drop into PNG Info not working

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#29]
just noticed that you can´t drag & drop an image into the PNG info, it will open the image instead.

![image](https://github.com/albertpb/sd-manager/assets/13394741/e26f7f1d-a972-472b-ab51-739bfa767eac)

**Comment by albertpb** [comment]
Fixed in v1.5.8

**Comment by AsuraAce** [comment]
drag&drop only works from windows file explorer it seems, tried from browser, other apps and SD-M itself, didn't work.
