### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#3]
checkpoint and ratings are displayed on top of each other. checkpoint name flows out of the frame as well in "rows 3" mode.

![image](https://github.com/albertpb/sd-manager/assets/13394741/b56f35ae-6069-4133-92e1-71511ce52e5f)

last row doesn´t fold correctly to the next row,

![image](https://github.com/albertpb/sd-manager/assets/13394741/e95c473a-19fc-4a09-8290-b9ff53e84f54)

"1 row" mode seems to be somewhat broken:

![image](https://github.com/albertpb/sd-manager/assets/13394741/548676ba-a229-4ff6-a5bf-a2aa2a834d86)

"2 row" mode seems to work fine but changes from portrait to tiles. should probably be a separate option instead.

![image](https://github.com/albertpb/sd-manager/assets/13394741/0e709015-1b50-4a49-a996-31493a531e76)

**Comment by albertpb** [comment]
Fixed in v1.5.0
