### ISSUE TITLE
can't turn off Auto Import "Animated On/Off" 

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#31]
it seems you can't turn this feature on and off

**Comment by albertpb** [comment]
I don't understand what option you are referring of. You mean this one 
![image](https://github.com/albertpb/sd-manager/assets/8062599/e8daea12-a1c6-4c38-951b-9619c742fa6a)
?

**Comment by AsuraAce** [comment]
can't show you right now, because i can't start SD-M.  i'm talking about the sidebar button (2nd or 3rd i believe from the top) in the image tab. if you hover over it it will tell you "animated on/off". 

i think this is tied to automatically importing newly generated images (watching the folder and updating the database)

**Comment by albertpb** [comment]
No, that buttons if for the hovering effect on the cards. When sd-manager starts will always check if there are new images that are not inserted in the database.
