### ISSUE TITLE
Image Import from InvokeAI throws error

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#34]
here is the error:

![image](https://github.com/albertpb/sd-manager/assets/13394741/d6cd47e1-d85a-452f-adea-18fe0ca56773)

here is the folder and the content:

![image](https://github.com/albertpb/sd-manager/assets/13394741/c14baee2-0c77-450e-b32d-3e7a8dee386d)

![image](https://github.com/albertpb/sd-manager/assets/13394741/3979f6ee-e022-480b-bee6-5d3ccbd56ba0)

**Comment by albertpb** [comment]
In what step, parsing, hashing or generating thumbnails ?

**Comment by AsuraAce** [comment]
hashing. here it looks like it is caused by a model but the error itself happened when i started updating the database after adding invokeAI's image folder and update the image database.

![image](https://github.com/albertpb/sd-manager/assets/13394741/a81808a7-ac1a-45a3-975b-867735d15ae2)

**Comment by albertpb** [comment]
InvokeAI generate the same image twice so I did a change when detecting images duplicated in v1.5.8. I don't know if that would fix it tho.

**Comment by AsuraAce** [comment]
- i'm able to start SD-Manager again
- images from invoke seem to be read (only checked newly generated ones)
- metadata can`t be read
- images are displayed two times (in SD-Manager as well as Breadboard)

![image](https://github.com/albertpb/sd-manager/assets/13394741/df1fc017-c4db-4f86-85ba-242857009276)

**Comment by albertpb** [comment]
InvokeAI generate the same image twice (related https://github.com/invoke-ai/InvokeAI/issues/4688). 
Can you share me the metadata ? I need the entire output from sd-manager png info.

**Comment by AsuraAce** [comment]
> InvokeAI generate the same image twice (related [invoke-ai/InvokeAI#4688](https://github.com/invoke-ai/InvokeAI/issues/4688)). Can you share me the metadata ? I need the entire output from sd-manager png info.

there is no output in the png info, already tried. i also tried a different prompt reader and Breadboard, same deal. checked within Invoke afterwards to see whether Invoke can read the metadata and it worked. 

i hope this works for you, otherwise let me know:
https://www.metadata2go.com/result#j=ed8dc093-6470-4dda-9ccd-d28ac84b634e

**Comment by albertpb** [comment]
yes thank you. Was failing because the json parser can't handle break lines (\n).
It will be fixed in the next version

**Comment by AsuraAce** [comment]
image import was fixed, not sure about the metadata, will check later and create a separate issues if the metadata still can't be read.
