### ISSUE TITLE
How is the Searchbar Working?

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#37]
not sure whether this is a bug or there is something i'm missing. search isn´t doing the most accurate job.

![image](https://github.com/albertpb/sd-manager/assets/13394741/af296db0-aa8a-45c8-8bbd-700dce358bc0)

![image](https://github.com/albertpb/sd-manager/assets/13394741/1319609a-c575-430f-b250-95b2e51a20f3)

**Comment by albertpb** [comment]
I'm using FuseJS to use fuzzy search. This is better that finding for the exact same pattern

**Comment by AsuraAce** [comment]
yep, agreed. fuzzy is better.
