### ISSUE TITLE
Lora Dupe Popup - Incorrectly Reading Duplicate Lora´s

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#4]
while some of the dupes are actually correct, most of them are not. below is one example for the esthetic90sStyle:

popup:

![image](https://github.com/albertpb/sd-manager/assets/13394741/218ceb3b-18d5-467b-a50e-71373265a525)

lora folder:

![image](https://github.com/albertpb/sd-manager/assets/13394741/497ae580-ff4b-4b73-ab55-b26891846fe2)

content from the esthetic90s folder:

![image](https://github.com/albertpb/sd-manager/assets/13394741/d35201b6-00d4-4a51-bfeb-273ad00cdd70)

**Comment by albertpb** [comment]
When detects a duplicate, it means the model (.ckpt or .safetensor file) has the same hash with another model and the hash has to unique to insert it on the database. Maybe I can clarify the message and tell you with which model collided.

**Comment by AsuraAce** [comment]
sounds good, thanks.

**Comment by albertpb** [comment]
Implemented in v1.5.1
