### ISSUE TITLE
Positive Prompt (Metadata) Incorrectly Read

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#40]
it seems there is something going on. sometimes the prompt is read incorrectly / not complete other times it is empty:

![image](https://github.com/albertpb/sd-manager/assets/13394741/b9646b81-197b-4ece-b0f7-940127f482e2)

![image](https://github.com/albertpb/sd-manager/assets/13394741/becbdecb-2220-469c-91b1-ea9c4bb4f3a3)

**Comment by albertpb** [comment]
give me the metada with www.metadata2go.com so I can test

**Comment by AsuraAce** [comment]
> give me the metada with [www.metadata2go.com](http://www.metadata2go.com) so I can test

here we go: https://www.metadata2go.com/result#j=a85cf75a-5635-4e87-a5a5-63048320f526

**Comment by AsuraAce** [comment]
seems to be fixed.
