### ISSUE TITLE
Change what Metadata is saved from Img2Img and Inpaint

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#41]
it should save the original prompt instead of the adjusted one.

example: 
original   prompt: "woman with blonde hair wearing a black suit"
img2img prompt: "pink hair"

SD-Manger would save "pink hair" but this has little (less than the alternative at least) value and is relevant for uploading images to sites that read your metadata / generation data like civitAI. right now the user would have to manually change the prompt for every image uploaded.

**Comment by albertpb** [comment]
sd-manager doesn't manipulate the original image, only reads the metadata. When you drag and drop, it paste the original image wherever you drop it.

**Comment by AsuraAce** [comment]
my bad, tested it with Breadboard and "it had the metadata from the previous image", it just so happened that i selected the wrong one.
