### ISSUE TITLE
Cant run?

### ISSUE THREAD

**Issue by JeffreyBull76** [albertpb/sd-manager#51]
Hi sorry for the stupid question but how do I run this, have downloaded/cloned the repo but all I have is json and js files, no executable or anything to run/compile this.

I know I'm missing something obvious but can't figure it out, any help appreciated.

**Comment by albertpb** [comment]
If you are on windows, download it from the release section or from this link https://github.com/albertpb/sd-manager/releases/download/v1.5.14/SD-Manager_win_v1.5.14.7z

For Linux or Mac (I haven't test it), you can install node (https://nodejs.org/en). clone the repo, run on a terminal npm install, then npm run start
