### ISSUE TITLE
No Metadata if Positive or Negative Prompt is Omitted

### ISSUE THREAD

**Issue by AsuraAce** [albertpb/sd-manager#6]
if the positive prompt is omitted when creating an image, SD-Manager won´t read / display the metadata. same is true if the negative prompt is omitted.

![image](https://github.com/albertpb/sd-manager/assets/13394741/2a2b1b43-39f6-46b4-a68f-20c940cf8dca)

![image](https://github.com/albertpb/sd-manager/assets/13394741/824f3454-79e7-4023-a563-ce7abf29f935)

**Comment by albertpb** [comment]
What did you use to generate the image ?

**Comment by AsuraAce** [comment]
> What did you use to generate the image ?

a1111

**Comment by albertpb** [comment]
Fixed in v1.5.4
If it keeps happening for some reason, open other issue.
